name: basit iş akışı

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Merhaba, dünya!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Merhaba, Dünya çok satırlı
          echo test, and deploy your project.
          echo Son satır.
          
